In [4]:
import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(3, 3)  # Example: 3 input neurons, 3 output neurons
        self.fc2 = nn.Linear(3, 3)  # Example: 3 input neurons, 3 output neurons
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Instantiate the model
model = SimpleNN()

# Manually set the weights for the first layer to [1, 2, 3, 4, 5, 6, 7, 8, 9]
# The weights tensor should match the shape of the layer's weight matrix
fixed_weights = torch.tensor([[1.0, 2.0, 3.0],
                              [4.0, 5.0, 6.0],
                              [7.0, 8.0, 9.0]])
model.fc1.weight.data = fixed_weights

# Optionally, you can also set biases if needed, for example to zeros
model.fc1.bias.data = torch.zeros(model.fc1.bias.size())

# Check the weights to ensure they are set correctly
for name, param in model.named_parameters():
    if 'weight' in name:
        print(f"{name} weights: {param.data}")
    elif 'bias' in name:
        print(f"{name} biases: {param.data}")

fc1.weight weights: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
fc1.bias biases: tensor([0., 0., 0.])
fc2.weight weights: tensor([[-0.1086,  0.3443,  0.4382],
        [ 0.0948,  0.4105, -0.0410],
        [ 0.4659, -0.4888,  0.1039]])
fc2.bias biases: tensor([-0.2957,  0.4160,  0.3593])


In [8]:
import numpy as np
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [9]:
weights_list = np.arange(0, 1, 0.1)
fixed_weights = torch.from_numpy(weights_list)
fixed_weights

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000], dtype=torch.float64)

In [23]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(1000, 1) 
        
    def forward(self, x):
        x = self.fc1(x)
        return x

# Instantiate the model
model = SimpleNN()

In [30]:
from torch.nn.parameter import Parameter

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(1000, 1) 
        
    def forward(self, x):
        x = self.fc1(x)
        return x

# Instantiate the model
model = SimpleNN()

fixed_weights = torch.linspace(-2, 2, 2000)
model.fc1.weight = Parameter(fixed_weights)

# Print the weights and bias to verify
print("Weights:", model.fc1.weight)
print("Bias:", model.fc1.bias)

Weights: Parameter containing:
tensor([-2.0000, -1.9980, -1.9960,  ...,  1.9960,  1.9980,  2.0000],
       requires_grad=True)
Bias: Parameter containing:
tensor([-0.0179], requires_grad=True)


In [17]:
num = 0
for name, param in model.named_parameters():
    if 'weight' in name:
        num =+1
        
        print(param)
        
print(num)

Parameter containing:
tensor([[-0.0022,  0.0149, -0.0046,  ..., -0.0024, -0.0120,  0.0080]],
       requires_grad=True)
1


In [27]:
from torch.nn.parameter import Parameter
from aihwkit.simulator.configs import InferenceRPUConfig

test_layer = nn.Linear(2000, 1)

linspace_tensor = torch.linspace(-2, 2, 2000)
forcing_tensor = Parameter(linspace_tensor)

test_layer.weight = forcing_tensor

rpu_config = InferenceRPUConfig()

print(rpu_config.device)

IdealDevice()
